name: Laravel Pint

on:
  pull_request:
    types: [ opened, reopened, edited, synchronize ]

jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: "laravel-pint"
          uses: aglipanci/laravel-pint-action@2.4
          with:
            preset: laravel
            verboseMode: true
            testMode: true
            useComposer: true
            configPath: './pint.json'
